The normal function takes two n-dimensional points, p1 and p2, and a distance parameter d and finds the midpoint between p1 and p2 that is the preportional distance as determined by d, where d represents the demical percentage of distance from p1 to p2.

For instance, if we took two one dimensional points:
- p1 = 0
- p2 = 10
- d = 0.5 (half way between the two points)

the function would output 5

likewise if we had:
- p1 = 1
- p2 = 10
- d = 0.5

the function would output 5.5

we can derive this function, as we want the preportioinal distance between p1 and p2, by subtracting p1 from p2, multiplying that by the percent distance, and adding p1

We can extrapolate the function to n dimension by performing this operation for each dimension component of the point.

In [40]:
import numpy as np

In [45]:
p1 = np.array([1,0])
p1

array([1, 0])

In [51]:
p1.shape

(2,)

In [46]:
p2 = np.array([5,5])
p2

array([5, 5])

In [49]:
(p2 - p1) * 0.5 + p1

array([3. , 2.5])

In [50]:
midpoint(list(p1),list(p2),0.5)

[3.0, 2.5]

In [53]:
def midpoint(p1,p2,d):
    return (p2-p1)*d+p1

In [33]:
def midpoint(p1,p2,d):
    assert len(p1) == len(p2), 'ERROR: The dimensions for p1 and p2 do not match'
    pr = []
    for i in range(len(p1)):
        pr.append(((p2[i] - p1[i])*d)+p1[i])
    return pr
        